package webadv.s162031.demo.entity;




import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 *留学审核实体类
 *
 * @author 杨磊
 * @since 2019-06-16
 */
/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "AbroadExam")
public class AbroadExam  {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)  
	private Integer apexId;
	@ManyToOne
    private AbroadApply abroadApply;
	@ManyToOne
    private Schoolmanage schoolRegister;
	private String apexStatus;
	public AbroadExam(Integer apexId, AbroadApply abroadApply, Schoolmanage schoolRegister, String apexStatus) {
		super();
		this.apexId = apexId;
		this.abroadApply = abroadApply;
		this.schoolRegister = schoolRegister;
		this.apexStatus = apexStatus;
	}
	public AbroadExam() {
		super();
	}
	public Integer getApexId() {
		return apexId;
	}
	public void setApexId(Integer apexId) {
		this.apexId = apexId;
	}
	public AbroadApply getAbroadApply() {
		return abroadApply;
	}
	public void setAbroadApply(AbroadApply abroadApply) {
		this.abroadApply = abroadApply;
	}
	public Schoolmanage getSchoolRegister() {
		return schoolRegister;
	}
	public void setSchoolRegister(Schoolmanage schoolRegister) {
		this.schoolRegister = schoolRegister;
	}
	public String getApexStatus() {
		return apexStatus;
	}
	public void setApexStatus(String apexStatus) {
		this.apexStatus = apexStatus;
	}
	






}
