package webadv.s162031.demo.entity;




import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 *留学要求实体类
 *
 * @author 杨磊
 * @since 2019-06-16
 */
/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "AbroadRequire")
public class AbroadRequire  {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)  
	private Integer arId;
	@ManyToOne
	private School school;
	private String arContent;
	private String arToefl;
	private String arIelts;
	private String arGre;
	private String arGamt;
	
	public AbroadRequire() {
		super();
	}
	public AbroadRequire(Integer arId, School school, String arContent, String arToefl, String arIelts, String arGre,
			String arGamt) {
		super();
		this.arId = arId;
		this.school = school;
		this.arContent = arContent;
		this.arToefl = arToefl;
		this.arIelts = arIelts;
		this.arGre = arGre;
		this.arGamt = arGamt;
	}
	public Integer getArId() {
		return arId;
	}
	public void setArId(Integer arId) {
		this.arId = arId;
	}
	public School getSchool() {
		return school;
	}
	public void setSchool(School school) {
		this.school = school;
	}
	public String getArContent() {
		return arContent;
	}
	public void setArContent(String arContent) {
		this.arContent = arContent;
	}
	public String getArToefl() {
		return arToefl;
	}
	public void setArToefl(String arToefl) {
		this.arToefl = arToefl;
	}
	public String getArIelts() {
		return arIelts;
	}
	public void setArIelts(String arIelts) {
		this.arIelts = arIelts;
	}
	public String getArGre() {
		return arGre;
	}
	public void setArGre(String arGre) {
		this.arGre = arGre;
	}
	public String getArGamt() {
		return arGamt;
	}
	public void setArGamt(String arGamt) {
		this.arGamt = arGamt;
	}
	




}
