package webadv.s162031.demo.entity;




import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 *留学申请实体类
 *
 * @author 杨磊
 * @since 2019-06-16
 */
/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "AbroadApply")
public class AbroadApply  {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)  
	private Integer apId;
	@ManyToOne
	private User user;
	@ManyToOne
	private School school;
	private String apPhone;
	private String apEmail;;
	private String apSchool1;
	private String apProfession1;
	private String apProfession2;
	private String apAvgscore;
	private String apContent;
	private String apToefl;
	private String apIelts;
	private String apGre;
	private String apGamt;
	
	
	public AbroadApply(Integer apId, User user, School school, String apPhone, String apEmail, String apSchool1,
			String apProfession1, String apProfession2, String apAvgscore, String apContent, String apToefl,
			String apIelts, String apGre, String apGamt) {
		super();
		this.apId = apId;
		this.user = user;
		this.school = school;
		this.apPhone = apPhone;
		this.apEmail = apEmail;
		this.apSchool1 = apSchool1;
		this.apProfession1 = apProfession1;
		this.apProfession2 = apProfession2;
		this.apAvgscore = apAvgscore;
		this.apContent = apContent;
		this.apToefl = apToefl;
		this.apIelts = apIelts;
		this.apGre = apGre;
		this.apGamt = apGamt;
	}

	public String getApPhone() {
		return apPhone;
	}

	public void setApPhone(String apPhone) {
		this.apPhone = apPhone;
	}

	public String getApEmail() {
		return apEmail;
	}

	public void setApEmail(String apEmail) {
		this.apEmail = apEmail;
	}

	public String getApContent() {
		return apContent;
	}

	public void setApContent(String apContent) {
		this.apContent = apContent;
	}

	public AbroadApply() {
		super();
	}

	public Integer getApId() {
		return apId;
	}
	public void setApId(Integer apId) {
		this.apId = apId;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public School getSchool() {
		return school;
	}
	public void setSchool(School school) {
		this.school = school;
	}
	public String getApSchool1() {
		return apSchool1;
	}
	public void setApSchool1(String apSchool1) {
		this.apSchool1 = apSchool1;
	}
	public String getApProfession1() {
		return apProfession1;
	}
	public void setApProfession1(String apProfession1) {
		this.apProfession1 = apProfession1;
	}
	public String getApProfession2() {
		return apProfession2;
	}
	public void setApProfession2(String apProfession2) {
		this.apProfession2 = apProfession2;
	}
	public String getApAvgscore() {
		return apAvgscore;
	}
	public void setApAvgscore(String apAvgscore) {
		this.apAvgscore = apAvgscore;
	}
	public String getApCotent() {
		return apContent;
	}
	public void setApCotent(String apData) {
		this.apContent = apData;
	}
	public String getApToefl() {
		return apToefl;
	}
	public void setApToefl(String apToefl) {
		this.apToefl = apToefl;
	}
	public String getApIelts() {
		return apIelts;
	}
	public void setApIelts(String apIelts) {
		this.apIelts = apIelts;
	}
	public String getApGre() {
		return apGre;
	}
	public void setApGre(String apGre) {
		this.apGre = apGre;
	}
	public String getApGamt() {
		return apGamt;
	}
	public void setApGamt(String apGamt) {
		this.apGamt = apGamt;
	}
	




}
